######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 3 00:32:48 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageIden.h
FORMS += imageIden.ui
SOURCES += imageIden.cpp main.cpp
