######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 12 16:07:27 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += planRoad.h
FORMS += planRoad.ui
SOURCES += main.cpp planRoad.cpp
