######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 2 15:53:22 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += configureMainWindow.h
FORMS += configureMainWindow.ui
SOURCES += configureMainWindow.cpp main.cpp
LIBS += -L. -lTQInputMethod

