######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 5 14:42:59 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += remoteSet.h
FORMS += remoteSet.ui
SOURCES += main.cpp remoteSet.cpp
