######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 3 16:16:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += avoid.h
FORMS += avoid.ui
SOURCES += avoid.cpp main.cpp
LIBS += -L. -lTQInputMethod
