######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 5 17:39:10 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../connection.h
SOURCES += tablemodel.cpp
QT +=sql
