######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 5 14:34:46 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += localSet.h
FORMS += localSet.ui
SOURCES += localSet.cpp main.cpp
LIBS += -L. -lTQInputMethod

