######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 20 14:20:12 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageIden.h TQInputMethod.h
FORMS += imageIden.ui
SOURCES += imageIden.cpp main.cpp
